### ISSUE TITLE
ensure isort runs locally

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/sixth_corp#107]
making sure we both have the same locally development setup. as a follow up item we could make isort cause travis failures.

mick already did this
this is just tracking for dvir to set it up

pip3 install isort
add an external tool to pycharm to run isort (notes in readme)

**Comment by dvirk** [comment]
I did pip install isort, and I can call `isort -rc src` in terminal before I push. Is there something else I need to do?
