### ISSUE TITLE
add notion of team/side and enforce this in can_use

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/sixth_corp#117]
can_use should prevent friendly fire an enemy shouldn't think it can laser its teammate, forexample

maybe we can add the notions of team and ability type so ability.can_use knows to check if it can use itself on other enemies, similarly for buffs

**Comment by dvirk** [comment]
The simplest way to do this is to give objects the `PLAYER_TEAM` state.

**Comment by dvirk** [comment]
Also see comment on #272
