### ISSUE TITLE
character_data should have initial mods

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/sixth_corp#153]
a character should be defined by chasis with slots and then initial mods for each of those slots, so character data should have a variable for chasis and a variable for initial mods. 

we shouldnt put too much in the chasis as it will make them less composable. i think it makes more sense for the attributes of the character to come from the chassis (health, battery, slots, etc) and the abilities to come from the mods.

**Comment by dvirk** [comment]
That's fine, we can just not give Chassis any inherent abilities.
