### ISSUE TITLE
implement player

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/sixth_corp#16]
required API

has_state(state : CharacterState) -> bool
has_attribute(attribute : CharacterAttribute) -> bool

**Comment by mick-warehime** [comment]
changing this to 
has_state
has_ability

**Comment by dvirk** [comment]
Ermm I was working on this. I thought this was assigned to me?

**Comment by mick-warehime** [comment]
It was but I needed it for combat scenes so I implemented a minimal
version. In retro spect I could have gotten away w just counters and hooked
up real characters later

**Comment by mick-warehime** [comment]
passing back to you. how did you think about implementing things like abilities? are those attributes? i was planning on the API being has_attribute, has_ability.

**Comment by dvirk** [comment]
I was thinking something like this:
```python
AttributeType = Union[Attribute, Ability]

class Ability(Enum):
    AGILITY: 'agility'
    STRENGTH: 'strength'
   ...
```
Then replace the `Attribute` type annotations with `AttributeType`.

**Comment by mick-warehime** [comment]
@dvirk is this done?
