### ISSUE TITLE
Respond to review of #174

### ISSUE THREAD

**Issue by dvirk** [mick-warehime/sixth_corp#176]
ref #174. I think it's better to pass more elementary information (`health:int`, `max_health: int`) as long as it doesn't get too cumbersome. This prevents unnecessary dependencies.

**Comment by mick-warehime** [comment]
i refactored how the views/screens are passed around and now we have conceptual isolation for things that get rendered to the screen and we have pygame isolated from the rest of the code behind the screen interface. 

i left the attribute.max_health and attribute.health for now in the views.artists.characterArtists class as this is now neatly isolated
