### ISSUE TITLE
change UI for selecting / visualizing subroutines

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/sixth_corp#202]
in the center of screen we can show the selected subroutines where t  = 0 is towards the top of the screen and t=inf towards the bottom

as the player shuffles through potential choices this display would update the resulting call graph (veritical lines with nodes for finished execution points) the nodes would have symbols like sword for a attack and shield for defend etc

once the player selects end turn their final choice will be locked in and the enemies choice will appear on the other half of the middle of the screen. the call graph will proceed.

**Comment by dvirk** [comment]
I think a version of this has been implemented.
