### ISSUE TITLE
tests should not run the ui

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/sixth_corp#254]
when i run the tests the ui launches and hangs

we should mock out pygame and run unit tests only during tests

**Comment by dvirk** [comment]
I intentionally included the Game() object in the integration tests only in order to have better test coverage.

**Comment by mick-warehime** [comment]
we should pull these out into their own tests. unit tests should be fast and not pull in the ui

**Comment by dvirk** [comment]
This is only in the integration tests, which are meant to mimic running the whole game. Where do you suggest we put it instead? In any case, they take 0.4 seconds on my laptop. The simulation tests take longer.

**Comment by mick-warehime** [comment]
Makes sense. It's ok where it is. Likely this is just my stale setup. We
can close this
