### ISSUE TITLE
Why not pytest?

### ISSUE THREAD

**Issue by dvirk** [mick-warehime/sixth_corp#3]
https://github.com/mick-warehime/sixth_corp/blob/d181d644e5aeb12003900a3405517b8520a9d318/src/keybindings_test.py#L1

**Comment by mick-warehime** [comment]
this gave me so many headaches last time i tried to integrate it with travis. i'm most familiar with unittest and its built-in. we can chat more about which to use and pros/cons if you like.

**Comment by mick-warehime** [comment]
Last time I struggled for hours working with pytest. i know i ran into a lot of issues trying to mock out pyqt crap which isnt relevant here. for now lets just use unittest unless you have a good reason not to. its one import and one class definition. i prefer the syntax of self.assertTrue, self.assertSetEqual, etc

**Comment by dvirk** [comment]
I'm going to add pytest to the requirements file. But you can keep using unittests because pytest will also run those automatically.
