### ISSUE TITLE
I thought we were going to make a text-based game protoype.

### ISSUE THREAD

**Issue by dvirk** [mick-warehime/sixth_corp#4]
https://github.com/mick-warehime/sixth_corp/blob/d181d644e5aeb12003900a3405517b8520a9d318/src/game.py#L12

I was thinking we would use something like [pyprompt_toolkit](https://python-prompt-toolkit.readthedocs.io/en/stable/index.html)

**Comment by mick-warehime** [comment]
this is a text-based game prototype. i decided to go back to pygame because it is easier to write text at a given location without learning a new library. we can also rip out the pygame part and replace with a CLI if you feel very strongly about it.

**Comment by mick-warehime** [comment]
i actually think pygame will be easier to present text - lets stick with it until it becomes a blocker
