### ISSUE TITLE
Merge some modules

### ISSUE THREAD

**Issue by dvirk** [mick-warehime/sixth_corp#5]
It seems to me that events.py, listener.py, event_listener.py, and event_manager.py can be merged into one module (events.py) for the moment. It's easier for me to review the code that way, at least. Perhaps we can merge Listener and EventListener?

**Comment by mick-warehime** [comment]
i used to have all of the code separated into packages but that became a pain for importing everything between packages so i went with a flat structure. im open to refactoring this stuff into folders.

for now i can merge this into one file but i think in general we should prefer smaller modules.
