### ISSUE TITLE
Controller class attributes

### ISSUE THREAD

**Issue by dvirk** [mick-warehime/sixth_corp#7]
https://github.com/mick-warehime/sixth_corp/blob/d181d644e5aeb12003900a3405517b8520a9d318/src/controller.py#L11

Are you sure you want the base Controller class to have model and view as class attributes? Because all controllers reference the same object. So instantiating a controller of type A then another controller of type B will make the model and view references of the former invalid.

**Comment by mick-warehime** [comment]
no - they should not be class level. ill update
