### ISSUE TITLE
Incorporate abilities into combat scene

### ISSUE THREAD

**Issue by dvirk** [mick-warehime/sixth_corp#70]
Enemy and player each have aggressive abilities. Each turn, player chooses an ability while enemy chooses an ability randomly. Both abilities are carried out at the same time (technically player ability happens first, but no other logic is implemented between). The view is updated with the ability descriptions, as well as player and enemy stats.

Components of issue:

1. Player abilities should be shown on the screen, implemented when chosen.
2. Enemy abilities should be chosen randomly and implemented.
3. Ability effects should be displayed.

**Comment by mick-warehime** [comment]
fixed with #82

**Comment by dvirk** [comment]
Dude, I thought I was working on this. I have a bit of work now that needs to be redone.

**Comment by dvirk** [comment]
Crap I forgot to assign to myself dammit.

**Comment by dvirk** [comment]
I'm going to open this up again because I think there are parts of this that haven't been addressed yet. I will assign it to myself if that is okay.

**Comment by mick-warehime** [comment]
Sorry. We should really really on the issues. This happened to me earlier
this week.

We should have narrowly scoped issues and rely on the ownerhsip. This will
improve over time as we refine the components and their organization.

Mainly I wanted to get the combat descriptions to depend on abilities in
the view / controllers. Get_moves(target) will facilititate building the
AI

**Comment by dvirk** [comment]
I guess I was thinking about it differently...

**Comment by dvirk** [comment]
Oops didn't mean to close.
