### ISSUE TITLE
add enemy examples

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/sixth_corp#71]
enemies should take an AI at construction

for now RandomAI is all we have

AI should be a class with the API
init(List[Abilities])
select_move(CombatHistory) -> Ability

randomAI would take an additional argument at construction (the probabilities of each ability, if none equal)

**Comment by dvirk** [comment]
For now I will include basic enemies that don't have AI.

**Comment by mick-warehime** [comment]
pr #131 has a drone class. it is trivial to add new enemies. just copy characters.enemies.drone and replace bits as needed
