### ISSUE TITLE
refactor abilities out of the combat controller/view/model

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/sixth_corp#90]
controller should only care about which player or enemy is selected and which skill is selected. the controller will pass this info to the model. the model should be a light weight class that manages a combatmanager

**Comment by mick-warehime** [comment]
related to #91

**Comment by dvirk** [comment]
I believe that is what the combat controller is more or less doing now. It worries about which ability (I think you are confusing that with skill)/which target is selected, and notifies the model and view accordingly.
