### ISSUE TITLE
add inventory scene

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/sixth_corp#96]
blocked by #94, #95 

have a screen that shows the chasis and mods equiped at each location
also should show the backpack
should allow for the player to swap out mods

**Comment by mick-warehime** [comment]
initial bit in #193

**Comment by dvirk** [comment]
[Sketch](https://docs.google.com/presentation/d/1fSHwM08BWy8bJyTFfCp16Rc1kQ0yTMhsf-1wD5oJQ84/edit#slide=id.g56764634d1_0_0) of inventory / loot scene.
