### ISSUE TITLE
Basic GUI layouts

### ISSUE THREAD

**Issue by dvirk** [mick-warehime/sixth_corp#99]
Make a VerticalLayout and HorizontalLayout class, which will allow one to control the layout of how things are blitted on the screen.  A layout should be able to contain other layouts. For now, all the layouts will do is draw a border around themselves.

API:
blit(screen) # for now this will just draw a border and call blit on all sub_layouts.
add_layout( sub_layout)

**Comment by mick-warehime** [comment]
Where did these GUI issues come from? What scenarios/features are they
blocking?

**Comment by dvirk** [comment]
I realized they are blocking the status overlay.

**Comment by mick-warehime** [comment]
There is a much cheaper way to implement that overlay. And the overlay
isn't super necessary. We can keep these but probably relatively low
priority.

**Comment by mick-warehime** [comment]
closing this - this isnt blocking anything we can add the status overlay directly if we need to
